ALTER TABLE pos_shop_settings
ADD COLUMN IF NOT EXISTS cover_url TEXT,
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS name_th TEXT,
ADD COLUMN IF NOT EXISTS name_en TEXT,
ADD COLUMN IF NOT EXISTS branch_name_th TEXT,
ADD COLUMN IF NOT EXISTS branch_name_en TEXT;
